# Generated by Django 4.1.7 on 2023-04-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_method',
            field=models.CharField(choices=[('IS', 'In Store'), ('HD', 'Home Delivery'), ('DD', 'Digital Delivery')], help_text='Required', max_length=255, verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_name',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='Delivery Name'),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, help_text='Maximum 999.99', max_digits=5, verbose_name='Delivery Price'),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_timeframe',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='Delivery Timeframe'),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_window',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='Delivery Window'),
        ),
        migrations.AlterField(
            model_name='paymentselections',
            name='title',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='Payment selection Name'),
        ),
    ]
