# Generated by Django 4.1.7 on 2023-04-08 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Brand Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Brand safe URL')),
                ('description', models.CharField(help_text='Required and unique', max_length=255, verbose_name='Brand Description')),
                ('logo', models.ImageField(default='images/default.png', help_text='Upload logo image', upload_to='images/brands/', verbose_name='Brand Logo')),
                ('web', models.CharField(max_length=255, verbose_name='Brand Website')),
                ('instagram', models.CharField(max_length=255, verbose_name='Brand Instagram')),
                ('twitter', models.CharField(max_length=255, verbose_name='Brand Twitter')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Category Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category safe URL')),
                ('description', models.CharField(help_text='Required and unique', max_length=255, verbose_name='Category Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category safe URL')),
                ('code', models.SlugField(max_length=255)),
                ('description', models.CharField(blank=True, help_text='Not Required', max_length=255, verbose_name='Discount description')),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value', max_digits=5, verbose_name='Discount Value')),
                ('value_unit', models.CharField(choices=[('PERC', 'Percent'), ('USD', 'USD')], help_text='Required', max_length=255, verbose_name='Value unit')),
                ('usable_once', models.BooleanField(default=False, help_text='Usable once?', verbose_name='Usable Once?')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Change discount visibility', verbose_name='Discount visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='Product title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category safe URL')),
                ('description', models.TextField(blank=True, help_text='Not required', null=True, verbose_name='Product description')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Retail Price')),
                ('retail_price_unit', models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'USD')], help_text='Required', max_length=255, null=True, verbose_name='Retail Price Value Unit')),
                ('initial_discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Required', max_digits=5, null=True, verbose_name='Initial Discount Value (if any)')),
                ('initial_discount_value_unit', models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'USD'), ('PERC', 'Percent')], help_text='Required', max_length=255, null=True, verbose_name='Initial Discount Value Unit')),
                ('is_active', models.BooleanField(default=True, help_text='Change product visibility', verbose_name='Product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.discount', verbose_name='Discount (if any)')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='Product Specification title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product Specification safe URL')),
                ('is_active', models.BooleanField(default=True, help_text='Change product specification visibility', verbose_name='Product specification visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Sub-category Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Sub-category safe URL')),
                ('description', models.CharField(help_text='Required and unique', max_length=255, verbose_name='Sub-category Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
            options={
                'verbose_name': 'Sub-category',
                'verbose_name_plural': 'Sub-categories',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('content', models.CharField(blank=True, help_text='Required', max_length=255, null=True, verbose_name='content')),
                ('stars', models.CharField(blank=True, choices=[('1', 'Very poor'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Good'), ('5', 'Very Good')], max_length=255, null=True, verbose_name='Stars')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category safe URL')),
                ('sku', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Not Required', verbose_name='description')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Purchase price')),
                ('purchase_price_unit', models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'USD')], help_text='Required', max_length=255, null=True, verbose_name='Purchase Price Value Unit')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Retail Price')),
                ('retail_price_unit', models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'USD')], help_text='Required', max_length=255, null=True, verbose_name='Retail Price Value Unit')),
                ('initial_discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Required', max_digits=5, null=True, verbose_name='Discount Value')),
                ('initial_discount_value_unit', models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'USD'), ('PERC', 'Percent')], help_text='Required', max_length=255, null=True, verbose_name='Initial Discount Value Unit')),
                ('sold', models.BooleanField(default=False, help_text='Change product availability', verbose_name='Sold?')),
                ('is_featured', models.BooleanField(default=True, help_text='Change as product default', verbose_name='Product default')),
                ('is_active', models.BooleanField(default=True, help_text='Change product visibility', verbose_name='Product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Unit',
                'verbose_name_plural': 'Product Units',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Product specification value (maximum of 255 words', max_length=255, verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productspecification')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productunit')),
            ],
            options={
                'verbose_name': 'Product Specification Value',
                'verbose_name_plural': 'Product Specification Values',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='images/products/', verbose_name='image')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product Specification safe URL')),
                ('alt_text', models.CharField(blank=True, help_text='Add an alternative text', max_length=255, null=True, verbose_name='Alternative text')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='inventory.productunit')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='users_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
