# Generated by Django 4.1.7 on 2023-04-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.FloatField(help_text='Discount value', verbose_name='Discount Value'),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_discount_value',
            field=models.FloatField(blank=True, help_text='Required', null=True, verbose_name='Initial Discount Value (if any)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Retail Price'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='retail_price',
            field=models.FloatField(verbose_name='Retail Price'),
        ),
    ]
