# Generated by Django 4.1.7 on 2023-04-09 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_alter_discount_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='title')),
                ('content', models.CharField(blank=True, help_text='Required', max_length=255, null=True, verbose_name='content')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product Review safe URL')),
                ('stars', models.CharField(blank=True, choices=[('1', 'Very poor'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Good'), ('5', 'Very Good')], max_length=255, null=True, verbose_name='Stars')),
                ('is_active', models.BooleanField(default=True, help_text='Change product review visibility', verbose_name='Product review visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductUnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='images/products/', verbose_name='image')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product Unit safe URL')),
                ('alt_text', models.CharField(blank=True, help_text='Add an alternative text', max_length=255, null=True, verbose_name='Alternative text')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Change product unit visibility', verbose_name='Product unit visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='added_by',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Change product specification value visibility', verbose_name='Product specification value visibility'),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='product',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True, verbose_name='Product Specification Value safe URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Change brand visibility', verbose_name='Brand visibility'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Change category visibility', verbose_name='Category visibility'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount value', max_digits=9, null=True, verbose_name='Discount Value'),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required', max_digits=9, null=True, verbose_name='Initial Discount Value (if any)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Retail Price'),
        ),
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='value',
            field=models.CharField(help_text='Product specification value (maximum of 255 words', max_length=255, verbose_name='Product Specification Value'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Change product unit visibility', verbose_name='Product Unit visibility'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Retail Price'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Change sub-category visibility', verbose_name='Sub-category visibility'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='productunitimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productunitimage',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
