# Generated by Django 4.1.7 on 2023-04-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productreview_productunitimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='product_specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specification', to='inventory.productspecification'),
        ),
    ]
