# Generated by Django 4.1.7 on 2023-04-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productspecificationvalue_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Product Specification safe URL'),
        ),
    ]
