# Generated by Django 4.1.7 on 2023-04-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productspecification_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='productunit',
            name='is_product_default',
            field=models.BooleanField(default=False, help_text='Change as product default', verbose_name='Product default'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.discount', verbose_name='Discount (if any) — (select discount code)'),
        ),
    ]
