# Generated by Django 4.1.7 on 2023-04-14 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_productunitimage_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='sku',
            field=models.SlugField(max_length=255, verbose_name='Stock Keeping Unit'),
        ),
        migrations.AlterField(
            model_name='productunitimage',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_unit_image', to='inventory.productunit'),
        ),
    ]
